"""PR yorumu: bir gözden geçirenin bilmesi gerekenler, kısa (`docs/02` §8).

Yorum ham eşik sayısı içermez; bulgu adını ve ölçülen değerin değişimini
söyler. Davranış testleri hatırlatması her yorumda: metrik iyileşmesi
testler geçmeden bir şey ifade etmez (invariant).
"""

from __future__ import annotations

from rlens.diff.compare import DiffResult
from rlens.verify.diff import ADDED, IMPROVED, MIXED, REGRESSED, REMOVED

#: Yorumda gösterilen en fazla satır; tamamı JSON raporunda.
MAX_ROWS = 15

_ORDER = {REGRESSED: 0, MIXED: 1, IMPROVED: 2, ADDED: 3, REMOVED: 4}


def _changes(entity) -> str:
    return ", ".join(
        f"{name} {delta.before}→{delta.after}" for name, delta in entity.changed_metrics.items()
    )


def _limited(lines: list[str]) -> list[str]:
    if len(lines) <= MAX_ROWS:
        return lines
    return [*lines[:MAX_ROWS], f"- … and {len(lines) - MAX_ROWS} more (see the JSON report)"]


def pr_comment(result: DiffResult) -> str:
    lines = [
        "## RefactorLens",
        "",
        f"`{result.base}` ({result.base_commit[:8]}) → `{result.head}` ({result.head_commit[:8]})",
        "",
    ]
    if not result.delta.comparable:
        lines += [f"> Not comparable: {result.delta.incompatibility}", ""]

    entities = sorted(
        (e for e in result.delta.entities if e.summarise() in _ORDER),
        key=lambda e: (_ORDER[e.summarise()], e.qualified_name),
    )
    if entities:
        rows = ["| Entity | Verdict | Changed metrics |", "|---|---|---|"]
        rows += [
            f"| `{e.qualified_name}` | {e.summarise()} | {_changes(e) or '—'} |"
            for e in entities[:MAX_ROWS]
        ]
        if len(entities) > MAX_ROWS:
            rows.append(f"| … {len(entities) - MAX_ROWS} more | | |")
        lines += ["### Metric changes", "", *rows, ""]
    else:
        lines += ["No metric changed.", ""]

    source = "the baseline" if result.accepted_from == "baseline" else f"`{result.base}`"
    if result.new_findings:
        lines += [
            f"### New findings ({len(result.new_findings)})",
            "",
            f"Not in {source}:",
            "",
            *_limited([f"- `{item}`" for item in result.new_findings]),
            "",
        ]
    if result.fixed_findings:
        lines += [
            f"### Resolved findings ({len(result.fixed_findings)})",
            "",
            *_limited([f"- `{item}`" for item in result.fixed_findings]),
            "",
        ]
    if result.refactorings:
        rows = []
        for item in result.refactorings:
            row = f"- {item.kind} {item.source} → {item.target} ({item.confidence:.2f})"
            wrappers = item.details.get("delegating_wrappers")
            if wrappers:
                row += f"; delegating wrappers left: {', '.join(wrappers)}"
            rows.append(row)
        lines += ["### Refactorings detected", "", *_limited(rows), ""]
    suspicious = result.goodhart.suspicious
    if suspicious:
        lines += [
            f"### Suspicious improvements ({len(suspicious)})",
            "",
            "Metrics improved while the public interface lost members:",
            "",
            *_limited([f"- `{check.qualified_name}`: {check.reason}" for check in suspicious]),
            "",
        ]
    lines += [
        "<sub>Metrics only mean something if the behaviour tests still pass. "
        "Generated by RefactorLens without any model call.</sub>",
        "",
    ]
    return "\n".join(lines)
